version: "3.9"

services:
  api:
    container_name: api_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database_dev
      - DB_PASSWORD=1234
      - DB_USER=developer
      - DB=backend-challenge
      - SECRET_KEY=secret
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: database_dev
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=backend-challenge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d backend-challenge"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    
  redis:
    container_name: redis_dev
    image: redis
    command: redis-server --requirepass 1234 --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
      - "13333:8001"
    volumes:
      - /home/duducp/Redis:/var/lib/postgresql/data